//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Atendiendo_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_Atendiendo_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\JOHNNY\AppData\Local\Temp\E74844360CDC80B9F9F41850D00A35B64366\4\CosultorioClinico\Capa1_Presentacion.Web.AspNet.ModuloPrincipal\Views\AtenderConsultas\Atendiendo.cshtml"
  
    ViewBag.Title = "Atendiendo";


#line default
#line hidden
DefineSection("customStyles", () => {

});

DefineSection("Scripts", () => {

});

}
}
}
